//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectPP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioAsignado
    {
        public int idServiceAsignado { get; set; }
        public System.DateTime fechaAsignado { get; set; }
        public int nroLegajo { get; set; }
        public int idService { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
