//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectPP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.ServicioAsignado = new HashSet<ServicioAsignado>();
        }
    
        public int idService { get; set; }
        public string nroService { get; set; }
        public string tipoService { get; set; }
        public Nullable<int> cantidadEquipos { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<System.DateTime> fechaPresupuestado { get; set; }
        public Nullable<System.DateTime> fechaPresupAprobado { get; set; }
        public int tecnicoACargo { get; set; }
        public int idCliente { get; set; }
        public int idEquipo { get; set; }
        public int idEstado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Equipo Equipo { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicioAsignado> ServicioAsignado { get; set; }
    }
}
